authors:
  Wcowin:
    name: gzh    # Author name
    description: Free and casual # Author description
    avatar: https://cdn.jsdelivr.net/gh/Gongzihang6/Pcitures@main/Medias/gzh.jpg # Author avatar
